<?php

declare(strict_types=1);

namespace App\Actions\Install\Linux;

use App\Data\Install\InstallContext;
use App\Services\Install\InstallLogger;
use HardImpact\Orbit\Core\Data\StepResult;
use Illuminate\Support\Facades\Process;

final readonly class TrustRootCa
{
    public function handle(InstallContext $context, InstallLogger $logger): StepResult
    {
        if ($context->skipTrust) {
            $logger->skip('Certificate trust skipped');

            return StepResult::success();
        }

        // First ensure Caddy CA is generated by running caddy trust
        $logger->step('Generating Caddy root certificate...');
        Process::run('caddy trust');

        // Use host-based Caddy certificate path
        $certPath = $_SERVER['HOME'].'/.local/share/caddy/pki/authorities/local/root.crt';

        if (! file_exists($certPath)) {
            $logger->warn('Caddy root certificate not found - certificates may not be trusted');
            $logger->info('Certificate expected at: '.$certPath);

            return StepResult::success();
        }

        // On Linux, add both root and intermediate to system trust store
        $rootTrusted = $this->addToLinuxTrustStore($certPath, 'orbit-caddy-root.crt', $logger);

        // Also trust intermediate CA (needed for site certificates)
        $intermediatePath = $_SERVER['HOME'].'/.local/share/caddy/pki/authorities/local/intermediate.crt';
        if (file_exists($intermediatePath)) {
            $this->addToLinuxTrustStore($intermediatePath, 'orbit-caddy-intermediate.crt', $logger);
        }

        if ($rootTrusted) {
            $logger->success('Certificate trusted');
        }

        return StepResult::success();
    }

    private function addToLinuxTrustStore(string $certPath, string $filename, InstallLogger $logger): bool
    {
        // Try update-ca-certificates (Debian/Ubuntu)
        if (file_exists('/usr/local/share/ca-certificates')) {
            $result = Process::run(
                "sudo cp \"{$certPath}\" /usr/local/share/ca-certificates/{$filename} && sudo update-ca-certificates"
            );

            if ($result->successful()) {
                return true;
            }
        }

        // Try trust anchor (Fedora/RHEL)
        if (file_exists('/etc/pki/ca-trust/source/anchors')) {
            $result = Process::run(
                "sudo cp \"{$certPath}\" /etc/pki/ca-trust/source/anchors/{$filename} && sudo update-ca-trust"
            );

            if ($result->successful()) {
                return true;
            }
        }

        $logger->warn('Could not automatically trust certificate: '.$filename);
        $logger->info('You may need to manually trust the certificate or run with sudo authorization');
        $logger->info('Certificate located at: '.$certPath);

        return false;
    }
}
